"""add_model_point_values

Revision ID: 12589288566b
Revises: 39a5ab22268c
Create Date: 2026-02-26 10:17:01.895324
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '12589288566b'
down_revision: Union[str, None] = '39a5ab22268c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variable', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('location_label', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('comparison', sa.String(length=4), nullable=False),
    sa.Column('consecutive_hours', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_variable'), 'alert_rules', ['variable'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('variable', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('location_label', sa.String(length=64), nullable=True),
    sa.Column('lead_hour', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_table('model_point_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('variable', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lead_hour', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'variable', 'lat', 'lon', 'lead_hour', name='uq_mpv_run_var_loc_fhr')
    )
    op.create_index(op.f('ix_model_point_values_lead_hour'), 'model_point_values', ['lead_hour'], unique=False)
    op.create_index(op.f('ix_model_point_values_run_id'), 'model_point_values', ['run_id'], unique=False)
    op.create_index(op.f('ix_model_point_values_variable'), 'model_point_values', ['variable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_point_values_variable'), table_name='model_point_values')
    op.drop_index(op.f('ix_model_point_values_run_id'), table_name='model_point_values')
    op.drop_index(op.f('ix_model_point_values_lead_hour'), table_name='model_point_values')
    op.drop_table('model_point_values')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alert_rules_variable'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
