"""initial

Revision ID: 39a5ab22268c
Revises: 
Create Date: 2026-02-25 21:36:10.042788
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39a5ab22268c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('init_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variable', sa.String(length=32), nullable=False),
    sa.Column('lead_hour', sa.Integer(), nullable=False),
    sa.Column('zarr_path', sa.String(length=512), nullable=False),
    sa.Column('bbox', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grid_snapshots_init_time'), 'grid_snapshots', ['init_time'], unique=False)
    op.create_index(op.f('ix_grid_snapshots_variable'), 'grid_snapshots', ['variable'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=16), nullable=False),
    sa.Column('init_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_hours', postgresql.ARRAY(sa.INTEGER()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'complete', 'error', name='runstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_init_time'), 'model_runs', ['init_time'], unique=False)
    op.create_index(op.f('ix_model_runs_model_name'), 'model_runs', ['model_name'], unique=False)
    op.create_table('point_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_a_id', sa.UUID(), nullable=False),
    sa.Column('run_b_id', sa.UUID(), nullable=False),
    sa.Column('variable', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lead_hour', sa.Integer(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('bias', sa.Float(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_a_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['run_b_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_metrics_lead_hour'), 'point_metrics', ['lead_hour'], unique=False)
    op.create_index(op.f('ix_point_metrics_run_a_id'), 'point_metrics', ['run_a_id'], unique=False)
    op.create_index(op.f('ix_point_metrics_run_b_id'), 'point_metrics', ['run_b_id'], unique=False)
    op.create_index(op.f('ix_point_metrics_variable'), 'point_metrics', ['variable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_metrics_variable'), table_name='point_metrics')
    op.drop_index(op.f('ix_point_metrics_run_b_id'), table_name='point_metrics')
    op.drop_index(op.f('ix_point_metrics_run_a_id'), table_name='point_metrics')
    op.drop_index(op.f('ix_point_metrics_lead_hour'), table_name='point_metrics')
    op.drop_table('point_metrics')
    op.drop_index(op.f('ix_model_runs_model_name'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_init_time'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_grid_snapshots_variable'), table_name='grid_snapshots')
    op.drop_index(op.f('ix_grid_snapshots_init_time'), table_name='grid_snapshots')
    op.drop_table('grid_snapshots')
    # ### end Alembic commands ###
